// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKIVVtrM9j-29_JNF6qK5hTjGxSZ3ZYEo',
    appId: '1:909244709530:android:4d11c50f932f428ed2fd23',
    messagingSenderId: '909244709530',
    projectId: 'lighthouse-7010a',
    storageBucket: 'lighthouse-7010a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCerPrsWVm9fNSzPP9Fss8nfps1gHqxWto',
    appId: '1:909244709530:ios:d1fc448ca6ccccc1d2fd23',
    messagingSenderId: '909244709530',
    projectId: 'lighthouse-7010a',
    storageBucket: 'lighthouse-7010a.appspot.com',
    androidClientId: '909244709530-293bs66pgk7qmqpk40un59thfdjspk4a.apps.googleusercontent.com',
    iosClientId: '909244709530-i9rlun4t8f50lml9h9goq7mar7kuoalb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterlogin',
  );
}
